package model;
// Generated 14/12/2016 11:35:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Compania generated by hbm2java
 */
@Entity
@Table(name="compania"
    ,catalog="museoplra"
)
public class Compania  implements java.io.Serializable {


     private Integer idComp;
     private Distrito distrito;
     private String nombrecomp;
     private Set barrios = new HashSet(0);

    public Compania() {
    }

	
    public Compania(Distrito distrito, String nombrecomp) {
        this.distrito = distrito;
        this.nombrecomp = nombrecomp;
    }
    public Compania(Distrito distrito, String nombrecomp, Set barrios) {
       this.distrito = distrito;
       this.nombrecomp = nombrecomp;
       this.barrios = barrios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idComp", unique=true, nullable=false)
    public Integer getIdComp() {
        return this.idComp;
    }
    
    public void setIdComp(Integer idComp) {
        this.idComp = idComp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Distrito_idDistri", nullable=false)
    public Distrito getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(Distrito distrito) {
        this.distrito = distrito;
    }

    
    @Column(name="nombrecomp", nullable=false, length=45)
    public String getNombrecomp() {
        return this.nombrecomp;
    }
    
    public void setNombrecomp(String nombrecomp) {
        this.nombrecomp = nombrecomp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="compania")
    public Set getBarrios() {
        return this.barrios;
    }
    
    public void setBarrios(Set barrios) {
        this.barrios = barrios;
    }




}


