package model;
// Generated 14/12/2016 11:35:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name="departamento"
    ,catalog="museoplra"
)
public class Departamento  implements java.io.Serializable {


     private Integer idDep;
     private Usuario usuario;
     private String nombredep;
     private Set distritos = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(Usuario usuario, String nombredep) {
        this.usuario = usuario;
        this.nombredep = nombredep;
    }
    public Departamento(Usuario usuario, String nombredep, Set distritos) {
       this.usuario = usuario;
       this.nombredep = nombredep;
       this.distritos = distritos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDep", unique=true, nullable=false)
    public Integer getIdDep() {
        return this.idDep;
    }
    
    public void setIdDep(Integer idDep) {
        this.idDep = idDep;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Usuario_idUsuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="nombredep", nullable=false, length=45)
    public String getNombredep() {
        return this.nombredep;
    }
    
    public void setNombredep(String nombredep) {
        this.nombredep = nombredep;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departamento")
    public Set getDistritos() {
        return this.distritos;
    }
    
    public void setDistritos(Set distritos) {
        this.distritos = distritos;
    }




}


