package model;
// Generated 22/11/2016 08:31:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Distrito generated by hbm2java
 */
@Entity
@Table(name="distrito"
    ,catalog="museoplra"
)
public class Distrito  implements java.io.Serializable {


     private Integer idDistri;
     private Departamento departamento;
     private String nombredistri;
     private Set companias = new HashSet(0);

    public Distrito() {
    }

	
    public Distrito(Departamento departamento, String nombredistri) {
        this.departamento = departamento;
        this.nombredistri = nombredistri;
    }
    public Distrito(Departamento departamento, String nombredistri, Set companias) {
       this.departamento = departamento;
       this.nombredistri = nombredistri;
       this.companias = companias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDistri", unique=true, nullable=false)
    public Integer getIdDistri() {
        return this.idDistri;
    }
    
    public void setIdDistri(Integer idDistri) {
        this.idDistri = idDistri;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Departamento_idDep", nullable=false)
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="nombredistri", nullable=false, length=45)
    public String getNombredistri() {
        return this.nombredistri;
    }
    
    public void setNombredistri(String nombredistri) {
        this.nombredistri = nombredistri;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="distrito")
    public Set getCompanias() {
        return this.companias;
    }
    
    public void setCompanias(Set companias) {
        this.companias = companias;
    }




}


