package model;
// Generated 22/11/2016 08:31:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="museoplra"
    , uniqueConstraints = {@UniqueConstraint(columnNames="usuario"), @UniqueConstraint(columnNames="password"), @UniqueConstraint(columnNames="Titular")} 
)
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Nivel nivel;
     private String usuario;
     private String password;
     private String titular;
     private Set departamentos = new HashSet(0);

    public Usuario() {
        this.idUsuario=0;
        this.nivel=new Nivel();
    }

	
    public Usuario(Nivel nivel, String usuario) {
        this.nivel = nivel;
        this.usuario = usuario;
    }
    public Usuario(Nivel nivel, String usuario, String password, String titular, Set departamentos) {
       this.nivel = nivel;
       this.usuario = usuario;
       this.password = password;
       this.titular = titular;
       this.departamentos = departamentos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idUsuario", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Nivel_idNivel", nullable=false)
    public Nivel getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Nivel nivel) {
        this.nivel = nivel;
    }

    
    @Column(name="usuario", unique=true, nullable=false, length=45)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="password", unique=true, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="Titular", unique=true, length=45)
    public String getTitular() {
        return this.titular;
    }
    
    public void setTitular(String titular) {
        this.titular = titular;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Set departamentos) {
        this.departamentos = departamentos;
    }




}


